# Copyright 2019 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-pipelines-admin
  labels:
    operator.openshift-pipelines.org/release: devel
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      operator.openshift-pipelines.org/controller: "true"
rules: [] # Rules are automatically filled in by the controller manager.

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-pipelines-core
  labels:
    operator.openshift-pipelines.org/release: devel
    operator.openshift-pipelines.org/controller: "true"
rules:
  # Allow creating events associated with resources we are controlling.
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]

  # Allow the reconciliation of exactly our validating webhooks.
  # This is needed for us to patch in caBundle information.
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["list", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["get", "update"]
    resourceNames: ["config.webhook.operator.openshift-pipelines.org", "validation.webhook.operator.openshift-pipelines.org"]

  # Allow the reconciliation of exactly our mutating webhooks.
  # This is needed for us to patch in caBundle information.
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["list", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["get", "update"]
    resourceNames: ["defaulting.webhook.operator.openshift-pipelines.org"]

  # Allow the reconciliation of exactly our CRDs.
  # This is needed for us to patch in conversion webhook information.
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "update"]
    resourceNames: ["simpledeployments.operator.openshift-pipelines.org"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "update"]
    resourceNames: ["tektonaddons.operator.tekton.dev", "tetkonchains.operator.tekton.dev", "tektonconfigs.operator.tekton.dev", "tektonhubs.operator.tekton.dev", "tektoninstallersets.operator.tekton.dev", "tektonpipelines.operator.tekton.dev", "tektontriggers.operator.tekton.dev"]

  # Allow us to reconcile our resources.
  - apiGroups: ["operator.openshift-pipelines.org"]
    resources: ["*"]
    verbs: ["get", "list", "update", "watch"]
    
  # The webhook configured the namespace as the OwnerRef on various cluster-scoped resources,
  # which requires we can Get the system namespace.
  # - apiGroups: [""]
  #   resources: ["namespaces"]
  #   verbs: ["get"]
  #   resourceNames: ["openshift-pipelines"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "update", "patch", "watch"]
  - apiGroups: [""]
    resources: [ "namespaces/finalizers" ]
    verbs: ["update"]

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # A separate cluster role for the things actually needed by this
  # controller's contrived examples.
  name: openshift-pipelines-resources
  labels:
    operator.openshift-pipelines.org/release: devel
    operator.openshift-pipelines.org/controller: "true"
rules:
  # AddressableService tracks services, so it needs to be able to list
  # and watch those in whatever namespace folks create those CRDs in
  # to do its job.
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]

  # SimpleDeployment creates and manages Pods, so it needs broad
  # permissions on pods
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "update", "delete", "watch"]

  - apiGroups:
    - operator.tekton.dev
    resources:
    - '*'
    - tektonaddons
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - patch
    - watch
  - apiGroups:
    - tekton.dev
    resources:
    - tasks
    - clustertasks
    - taskruns
    - pipelines
    - pipelineruns
    - pipelineresources
    - conditions
    - tasks/status
    - clustertasks/status
    - taskruns/status
    - pipelines/status
    - pipelineruns/status
    - pipelineresources/status
    - taskruns/finalizers
    - pipelineruns/finalizers
    - runs
    - runs/status
    - runs/finalizers
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - patch
    - watch
  - apiGroups:
    - triggers.tekton.dev
    - operator.tekton.dev
    resources:
    - '*'
    verbs:
    - add
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - patch
    - watch
  - apiGroups:
    - security.openshift.io
    resources:
    - securitycontextconstraints
    verbs:
    - use
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
    - deployments/finalizers
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - patch
    - watch
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    verbs:
    - get
    - create
    - delete
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - clusterroles
    - roles
    verbs:
    - get
    - create
    - update
    - delete
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
  - apiGroups:
    - ""
    resources:
    - namespaces/finalizers
    verbs:
    - update
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - events
    - configmaps
    - secrets
    - pods/log
    - limitranges
    verbs:
    - delete
    - deletecollection
    - create
    - patch
    - get
    - list
    - update
    - watch
  - apiGroups:
    - extensions
    - apps
    resources:
    - ingresses
    - ingresses/status
    verbs:
    - delete
    - create
    - patch
    - get
    - list
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
    - deployments/finalizers
    verbs:
    - delete
    - deletecollection
    - create
    - patch
    - get
    - list
    - update
    - watch
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    verbs:
    - get
    - create
    - delete
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - clusterroles
    - roles
    verbs:
    - delete
    - deletecollection
    - create
    - patch
    - get
    - list
    - update
    - watch
    - bind
    - escalate
  - apiGroups:
    - ""
    resources:
    - serviceaccounts
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
    - impersonate
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - clusterrolebindings
    - rolebindings
    verbs:
    - get
    - create
    - update
    - delete
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    - customresourcedefinitions/status
    verbs:
    - get
    - create
    - update
    - delete
    - list
    - patch
    - watch
  - apiGroups:
    - admissionregistration.k8s.io
    resources:
    - mutatingwebhookconfigurations
    - validatingwebhookconfigurations
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
  - apiGroups:
    - build.knative.dev
    resources:
    - builds
    - buildtemplates
    - clusterbuildtemplates
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
  - apiGroups:
    - extensions
    resources:
    - deployments
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
  - apiGroups:
    - extensions
    resources:
    - deployments/finalizers
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
  - apiGroups:
    - policy
    resources:
    - podsecuritypolicies
    verbs:
    - get
    - create
    - update
    - delete
    - use
  - apiGroups:
    - operator.tekton.dev
    resources:
    - '*'
    - tektonaddons
    verbs:
    - delete
    - deletecollection
    - create
    - patch
    - get
    - list
    - update
    - watch
  - apiGroups:
    - tekton.dev
    - triggers.tekton.dev
    - operator.tekton.dev
    resources:
    - '*'
    verbs:
    - add
    - delete
    - deletecollection
    - create
    - patch
    - get
    - list
    - update
    - watch
  - apiGroups:
    - dashboard.tekton.dev
    resources:
    - '*'
    - tektonaddons
    verbs:
    - delete
    - deletecollection
    - create
    - patch
    - get
    - list
    - update
    - watch
  - apiGroups:
    - security.openshift.io
    resources:
    - securitycontextconstraints
    verbs:
    - use
    - get
    - create
    - update
    - delete
  - apiGroups:
    - route.openshift.io
    resources:
    - routes
    verbs:
    - delete
    - deletecollection
    - create
    - patch
    - get
    - list
    - update
    - watch
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
  - apiGroups:
    - console.openshift.io
    resources:
    - consoleyamlsamples
    - consoleclidownloads
    - consolequickstarts
    - consolelinks
    verbs:
    - delete
    - deletecollection
    - create
    - patch
    - get
    - list
    - update
    - watch
  - apiGroups:
    - autoscaling
    resources:
    - horizontalpodautoscalers
    verbs:
    - delete
    - create
    - patch
    - get
    - list
    - update
    - watch
  - apiGroups:
    - policy
    resources:
    - poddisruptionbudgets
    verbs:
    - delete
    - deletecollection
    - create
    - patch
    - get
    - list
    - update
    - watch
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    verbs:
    - delete
    - deletecollection
    - create
    - patch
    - get
    - list
    - update
    - watch
  - apiGroups:
    - batch
    resources:
    - jobs
    - cronjobs
    verbs:
    - delete
    - deletecollection
    - create
    - patch
    - get
    - list
    - update
    - watch
    # finalizers are needed for the owner reference of the webhook
  - apiGroups:
    - ""
    resources:
    - "namespaces/finalizers"
    verbs:
    - "update"
  - apiGroups:
    - resolution.tekton.dev
    resources:
    - resolutionrequests
    verbs:
    - get
    - list
    - watch
    - create
    - delete


